interface ritArray extends OBject {
    tijd: number,
    afstand: number,
    matnummer: String,
    ritnummer: number,
    ritserie: number,
    starttijd: string,
    eindtijd: string,
    starttijdUnix: number,
    eindtijdUnix: number,
    planStarttijdUnix: number,
    planEindTijdUnix: number,
    planStarttijd: string,
    planEindTijd: string,
    startPunt: string,
    startPuntSpoor: number,
    eindPunt: string,
    eindPuntSpoor: number,
    startVertraging: number,
    eindVertraging: number,
}